image : "rdieg/basics:latest"

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script: 
    - qmake "CONFIG += optimize_full" "CONFIG += release"
    - make
  artifacts:
    paths:
      - RedBlack

test:
  stage: test
  tags:
    - docker

  script:
    - ./RedBlack
