image : "rdieg/basics:latest"

build:
  stage: build
  tags:
    - docker
  script: g++ /tests/tests.cpp -o mybinary
  artifacts:
    paths:
      - mybinary

test:
  stage: test
  tags:
    - docker

  script:
    - ./mybinary

